server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ridedriveahead}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgrespassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

ridedriveahead:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-token-expiration-ms: 86400000 # 24 hours
    refresh-token-expiration-ms: 2592000000 # 30 days
  auth:
    mock-otp-enabled: true
    default-otp: "123456"
  security:
    vault-secret: MasterKycVaultSecretKeyMustBe32BytesLength2026!

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ridedriveahead: DEBUG
    org.springframework.security: INFO
