server:
  port: 8083

spring:
  application:
    name: driver-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ridedriveahead}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgrespassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

ridedriveahead:
  security:
    vault-secret: MasterKycVaultSecretKeyMustBe32BytesLength2026!
  safety:
    max-daily-driving-hours: 8.0
    continuous-driving-limit-hours: 4.0
    recommended-rest-minutes: 45

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ridedriveahead: DEBUG
