server:
  port: 8084

spring:
  application:
    name: payment-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ridedriveahead: DEBUG
